In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_curve, auc
from sklearn import grid_search
from sklearn import cross_validation
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from IPython.display import display
from IPython.core.pylabtools import getfigs

sns.set_context('talk')
sns.set_style('whitegrid') 


In [2]:
%matplotlib qt

In [3]:
X_df = pd.read_pickle('new_X_df.save')
outcomes_df = pd.read_pickle('new_outcomes_df.save')

In [4]:
np.shape(X_df)

(115196, 38)

In [6]:
pred_subset_smaller = ['Goal','N_creator_backed','N_rewards','Body_n_words',\
                       'Ships_intn','Min_reward', 'Median_reward', 'Max_reward',\
                       'art', 'comics', 'crafts', 'dance', 'design', 'fashion',\
                       'film', 'food', 'games', 'journalism', 'music', 'photography',\
                       'publishing', 'technology', 'theater',]

In [7]:
X_subset_df = X_df[pred_subset_smaller]

In [8]:
X_subset_df.head(2)

Goal N_creator_backed N_rewards Body_n_words  Ships_intn Min_reward  \
0   5000               18         8          812           0         10   
1  10000                7        10          792           0          5   

  Median_reward Max_reward  art  comics   ...     fashion  film  food  games  \
0           175       5000    0       0   ...           0     0     0      0   
1           125       5000    0       0   ...           0     0     0      0   

   journalism  music  photography  publishing  technology  theater  
0           0      0            0           0           0        1  
1           0      0            0           0           0        1  

[2 rows x 23 columns]

In [208]:
print list(small_X_df.columns)

['Goal', 'N_creator_backed', 'N_rewards', 'Body_n_words', 'Ships_intn', 'Min_reward', 'Median_reward', 'Max_reward', 'art', 'comics', 'crafts', 'dance', 'design', 'fashion', 'film', 'food', 'games', 'journalism', 'music', 'photography', 'publishing', 'technology', 'theater']


In [9]:
outcomes_df.head()

Outcome
0        1
1        1
2        1
3        1
4        1

In [17]:
success_is = np.where(outcomes_df['Outcome'])[0]
fail_is = np.where(outcomes_df['Outcome'] == 0)[0]

In [19]:
print np.shape(success_is),np.shape(fail_is)

(47620,) (67576,)


In [27]:
# look at N_creator_backed

In [23]:
np.mean(X_subset_df.ix[success_is,'N_creator_backed'])

8.71352372952541

In [24]:
np.mean(X_subset_df.ix[fail_is,'N_creator_backed'])

2.8698650408429027

In [25]:
import scipy
scipy.stats.mstats.mquantiles(X_subset_df.ix[success_is,'N_creator_backed'])

array([1.0, 3.0, 8.0], dtype=object)

In [26]:
scipy.stats.mstats.mquantiles(X_subset_df.ix[fail_is,'N_creator_backed'])

array([0.0, 0.0, 2.0], dtype=object)

In [28]:
# look at Body_n_words

In [30]:
scipy.stats.mstats.mquantiles(X_subset_df.ix[success_is,'Body_n_words'])

array([405.0, 658.0, 1095.0], dtype=object)

In [31]:
scipy.stats.mstats.mquantiles(X_subset_df.ix[fail_is,'Body_n_words'])

array([271.0, 484.0, 865.0], dtype=object)

In [32]:
# look at N rewards
scipy.stats.mstats.mquantiles(X_subset_df.ix[success_is,'N_rewards'])

array([6.0, 9.0, 13.0], dtype=object)

In [33]:
scipy.stats.mstats.mquantiles(X_subset_df.ix[fail_is,'N_rewards'])

array([4.0, 7.0, 10.0], dtype=object)

In [34]:
# look at goal by category -- pickle this
scipy.stats.mstats.mquantiles(X_subset_df.ix[fail_is,'Goal'])

array([3000.0, 7500.0, 20000.0], dtype=object)

In [35]:
scipy.stats.mstats.mquantiles(X_subset_df.ix[success_is,'Goal'])

array([1500.0, 4000.0, 10000.0], dtype=object)